import type { ProviderCapabilities, ProviderName } from '@crm/messaging-schema';

// ── Meta Cloud API ────────────────────────────────────────────────────────────
// Sources: https://developers.facebook.com/docs/whatsapp/cloud-api/messages
// Limits as of Graph API v21.0.

export const META_CAPABILITIES: ProviderCapabilities = {
  kinds: {
    text:                     { inbound: true,  outbound: true  },
    media:                    { inbound: true,  outbound: true  },
    template:                 { inbound: false, outbound: true,  notes: 'Requires Meta WABA approval before sending' },
    interactive_buttons:      { inbound: false, outbound: true  },
    interactive_list:         { inbound: false, outbound: true  },
    interactive_cta:          { inbound: false, outbound: true  },
    interactive_product:      { inbound: false, outbound: true,  notes: 'Requires WhatsApp Catalog integration' },
    interactive_product_list: { inbound: false, outbound: true,  notes: 'Requires WhatsApp Catalog integration' },
    location:                 { inbound: true,  outbound: true  },
    contact_card:             { inbound: true,  outbound: true  },
    order:                    { inbound: true,  outbound: false, notes: 'Orders are inbound-only (customer → business)' },
    system:                   { inbound: true,  outbound: false, notes: 'System events are generated by the platform' },
    unknown:                  { inbound: true,  outbound: false },
  },

  buttonLimits: {
    quickReplyMax:      3,   // Meta hard limit
    quickReplyTitleMax: 20,  // chars
    ctaMax:             1,   // one CTA URL per interactive_cta
  },

  listLimits: {
    sectionsMax:       10,
    rowsPerSectionMax: 10,
    rowTitleMax:       24,  // chars
  },

  mediaLimits: {
    image:    { sizeMaxMb: 5,   mimeWhitelist: ['image/jpeg', 'image/png'] },
    video:    { sizeMaxMb: 16,  mimeWhitelist: ['video/mp4', 'video/3gpp'] },
    audio:    { sizeMaxMb: 16,  mimeWhitelist: ['audio/mpeg', 'audio/ogg', 'audio/aac', 'audio/mp4', 'audio/amr'] },
    voice:    { sizeMaxMb: 16,  mimeWhitelist: ['audio/ogg'] },
    document: { sizeMaxMb: 100, mimeWhitelist: [] },  // any MIME for documents
    sticker:  { sizeMaxMb: 0.1, mimeWhitelist: ['image/webp'] },
  },

  sessionWindow: { hours: 24 },

  templates: { supported: true, requiresApproval: true },
  reactions: { supported: true },

  defaultMode: 'cloud_api',
};

// ── Baileys (unofficial WhatsApp Web API) ─────────────────────────────────────
// Baileys mirrors real WhatsApp Web which has no official interactive message
// support. Buttons and list messages are possible via undocumented proto fields
// but are routinely blocked by WhatsApp server-side — treat as unsupported.

export const BAILEYS_CAPABILITIES: ProviderCapabilities = {
  kinds: {
    text:                     { inbound: true,  outbound: true  },
    media:                    { inbound: true,  outbound: true  },
    template:                 { inbound: false, outbound: false, notes: 'No Meta approval flow; use fallback_text mode to send as plain text' },
    interactive_buttons:      { inbound: true,  outbound: false, notes: 'Sending via unofficial proto is routinely blocked by WhatsApp' },
    interactive_list:         { inbound: true,  outbound: false, notes: 'Sending via unofficial proto is routinely blocked by WhatsApp' },
    interactive_cta:          { inbound: false, outbound: false },
    interactive_product:      { inbound: false, outbound: false },
    interactive_product_list: { inbound: false, outbound: false },
    location:                 { inbound: true,  outbound: true  },
    contact_card:             { inbound: true,  outbound: true  },
    order:                    { inbound: true,  outbound: false },
    system:                   { inbound: true,  outbound: false },
    unknown:                  { inbound: true,  outbound: false },
  },

  // Buttons are not reliably deliverable; limits are 0 to prevent sends.
  buttonLimits: {
    quickReplyMax:      0,
    quickReplyTitleMax: 0,
    ctaMax:             0,
  },

  listLimits: {
    sectionsMax:       0,
    rowsPerSectionMax: 0,
    rowTitleMax:       0,
  },

  mediaLimits: {
    image:    { sizeMaxMb: 16,  mimeWhitelist: [] },
    video:    { sizeMaxMb: 16,  mimeWhitelist: [] },
    audio:    { sizeMaxMb: 16,  mimeWhitelist: [] },
    voice:    { sizeMaxMb: 16,  mimeWhitelist: ['audio/ogg'] },
    document: { sizeMaxMb: 100, mimeWhitelist: [] },
    sticker:  { sizeMaxMb: 0.5, mimeWhitelist: ['image/webp'] },
  },

  sessionWindow: { hours: 24 },

  templates: { supported: false, requiresApproval: false },
  reactions: { supported: true },

  defaultMode: 'fallback_text',
};

// ── Capability registry ───────────────────────────────────────────────────────

const REGISTRY: Record<ProviderName, ProviderCapabilities> = {
  meta:       META_CAPABILITIES,
  baileys:    BAILEYS_CAPABILITIES,
  // Forward-compatible: unknown providers fall back to most-restrictive caps.
  twilio:     BAILEYS_CAPABILITIES,
  '360dialog': META_CAPABILITIES,
};

export function getCapabilities(provider: ProviderName): ProviderCapabilities {
  return REGISTRY[provider] ?? BAILEYS_CAPABILITIES;
}
